/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulometjacobiu3metnum;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author Adrian
 */
public class JFMetJacobiU3MetNum extends javax.swing.JFrame implements TableModelListener {

    JFPreDatoMetJacobiU3MetNum r = new JFPreDatoMetJacobiU3MetNum();

    // Definimos tres arreglos para guardar los datos de la tabla 
    
    double A[][]= new double[JFPreDatoMetJacobiU3MetNum.numFilasMatriz][JFPreDatoMetJacobiU3MetNum.numColumnasMatriz];
    double X[]= new double[JFPreDatoMetJacobiU3MetNum.numFilasMatriz];
    double C[]= new double[JFPreDatoMetJacobiU3MetNum.numFilasMatriz];
    double aux[]=new double[JFPreDatoMetJacobiU3MetNum.numFilasMatriz];
      double aux2[]=new double[JFPreDatoMetJacobiU3MetNum.numFilasMatriz];
       double aux3[]=new double[JFPreDatoMetJacobiU3MetNum.numFilasMatriz];
      String MatrizF[][]= new String[JFPreDatoMetJacobiU3MetNum.numFilasMatriz][JFPreDatoMetJacobiU3MetNum.numIteraciones];
  
         
    /**
     * Creates new form JFMetJacobiU3MetNum
     */
    public JFMetJacobiU3MetNum() {
        initComponents();
        //Definir que la ventana aparezca desde el centro de la pantalla...
        setLocationRelativeTo(this);
        //Definimos las dimensiones de las tablas A, X y C (Vectores resultantes del problema)...
        String[] titulos = new String[JFPreDatoMetJacobiU3MetNum.numColumnasMatriz];
        for (int contador = 0; contador < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; contador++) {

            titulos[contador] = "X" + (contador + 1);
        }
        String[] x = new String[1];
        x[0] = "X";
        String[] c = new String[1];
        c[0] = "C";

        frmTablaAbs modelo = new frmTablaAbs(r.datos, titulos);
        frmTablaAbs modelo2 = new frmTablaAbs(r.datos, x);
        frmTablaAbs modelo3 = new frmTablaAbs(r.datos, c);
        //DefaultTableModel  x = new DefaultTableModel(5,6);
        jTable1.setModel(modelo);
        jTable2.setModel(modelo2);
        jTable3.setModel(modelo3);
        
       jTable4.setModel(tabla);
        /*jTable1.setModel(new ValoresMetJacobiTableModel('A',JFPreDatoMetJacobiU3MetNum.numFilasMatriz,JFPreDatoMetJacobiU3MetNum.numColumnasMatriz));
        jTable1.getModel().addTableModelListener(this);
        jTable2.setModel(new ValoresMetJacobiTableModel('X',JFPreDatoMetJacobiU3MetNum.numFilasMatriz,1));
        jTable3.setModel(new ValoresMetJacobiTableModel('C',JFPreDatoMetJacobiU3MetNum.numFilasMatriz,1));
        
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("VACIADO DE LOS DATOS EN EL VECTOR BASE, INICIAL Y C");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MÉTODO DE JACOBI");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("METNUM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)))
                .addGap(198, 198, 198))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setText("a) Vector base con valores Xn");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel5.setText("b) Vector inicial");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setText("c) Vector C");

        jButton1.setText("CALCULAR ITERACIONES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel7.setText("VALORACIÓN DE RESULTADOS:");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel7))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        
        for (int fil = 0; fil < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; fil++) {

            for (int col = 0; col < JFPreDatoMetJacobiU3MetNum.numColumnasMatriz; col++) {
                    String  test= (String) jTable1.getValueAt(fil, col);
                this.A[fil][col]=Double.parseDouble(test); 
                System.out.print( this.A[fil][col]+ ", ");
                 // System.out.print( test+ ", ");
            }
            System.out.println();
        }
        System.out.println();

        for (int fil = 0; fil < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; fil++) {
                String  test= (String) jTable2.getValueAt(fil, 0);
                this.X[fil]=Double.parseDouble(test);
            System.out.print(this.X[fil] + ", ");
        }
          System.out.println();
        for (int fil = 0; fil < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; fil++) {
            String  test= (String)jTable3.getValueAt(fil,0);
            this.C[fil]= Double.parseDouble(test);
            System.out.print( this.C[fil]+ ", ");
        }
        System.out.println();
        System.out.println("----------------------");
     
      /*
       for (int fil = 0; fil < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; fil++) {
            System.out.print(  this.aux[fil]);
        }
       */
         System.out.println();
         
         
        /* for (int fil = 0; fil < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; fil++) {
              System.out.print(this.aux[fil]); 
        }
         this.aux2=this.aux;
          System.out.println("-------------------------------");
        aux3= met.multVect(A, aux2, C);
         
         for (int fil = 0; fil < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; fil++) {
              System.out.print(this.aux3[fil]);  
        }
         
         
         System.out.println("-------------------------------");
         */
        
        
        // SOLO LO ENTIENDE EDUARDO XDXD
        // TODOS LOS DERECHOS RESERVADOS JAJAJA
        this.aux= met.multVect(A, X, C);
        this.aux2= met.multVect(A, X, C);
        for(int id= 0; id< JFPreDatoMetJacobiU3MetNum.numIteraciones; id++)
       {
         
             for(int pas= 0; pas <  JFPreDatoMetJacobiU3MetNum.numFilasMatriz; pas++)
             {
               this.aux3[pas]= this.aux[pas];
              // System.out.print( aux3[pas]  +" ," );  
                 /*This.aux2= met.multVect(A,this.aux, C);
              System.out.print( aux2[pas]  +" ," );
              */
                 this.MatrizF[pas][id]= String.valueOf(this.aux2[pas]);
                 // linea donde se imprimen los datos
                  System.out.print( aux2[pas]  +" ," );  
               // aux es el arreglo donde estan los datos calculados
             

               
            
             }
              
             this.aux2=  met.multVect(A, this.aux3, C);  
            
              System.out.println();
       }
         System.out.println("------------");
         for(int id= 0; id< JFPreDatoMetJacobiU3MetNum.numFilasMatriz; id++)
       {
         
             for(int pas= 0; pas <  JFPreDatoMetJacobiU3MetNum.numIteraciones; pas++)
             {
               
             System.out.print(this.MatrizF[id][pas]+" | ");
             }
           System.out.println();
       }
        
         jTable4.setModel(new DefaultTableModel(MatrizF, tabla.generador('R',JFPreDatoMetJacobiU3MetNum.numFilasMatriz,JFPreDatoMetJacobiU3MetNum.numIteraciones) ));
        
       
         //jTable4.setModel(new  DefaultTableModel);
        
        
      
          
          // TableColumn c=jTable4.getColumnModel().getColumn(1);
           
         
              /* JComboBox combo=new JComboBox(xd);        
             TableColumn c = jTable4.getColumnModel().getColumn(1);
              TableCellEditor tce= new DefaultCellEditor(combo);
                c.setCellEditor(tce);*/
         System.out.println();
       }
       
      
    
    
       
       
       
    
       catch (Exception ex)
               {
               
               JOptionPane.showMessageDialog(null, "HUBO UN ERROR AL PROCESAR LOS DATOS :("+ex);
               }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JFPreDatoMetJacobiU3MetNum ventana=new JFPreDatoMetJacobiU3MetNum();
        ventana.show();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMetJacobiU3MetNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMetJacobiU3MetNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMetJacobiU3MetNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMetJacobiU3MetNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMetJacobiU3MetNum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
        for (int contador = 0; contador < JFPreDatoMetJacobiU3MetNum.numFilasMatriz; contador++) {
            for (int contador1 = 0; contador1 < JFPreDatoMetJacobiU3MetNum.numColumnasMatriz; contador1++) {
                jTable1.setValueAt(jTable1.getValueAt(contador, contador1), contador, contador1);
            }
        }
    }
    JFPreDatoMetJacobiU3MetNum im = new JFPreDatoMetJacobiU3MetNum();
clsMetodos  met=new  clsMetodos ();
ValoresMetJacobiTableModel tabla=new ValoresMetJacobiTableModel('R',JFPreDatoMetJacobiU3MetNum.numFilasMatriz,JFPreDatoMetJacobiU3MetNum.numIteraciones);
}
